hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 2048
  max_response_length: 2048
  train_batch_size: 64
  return_raw_chat: True
  return_multi_modal_inputs: True
  custom_cls:
    path: "recipe/vlm_subagent/vlm_subagent.py"
    name: CustomRLHFDataset

actor_rollout_ref:
  hybrid_engine: True
  # model:
    # Use the model's default chat template (handles system messages correctly)
  rollout:
    name: vllm
    multi_turn:
      enable: True
      max_assistant_turns: 5
      tool_config_path: "recipe/vlm_subagent/configs/vlm_subagent_tool_config.yaml"

custom_reward_function:
  path: "recipe/vlm_subagent/vlm_subagent.py"
  name: compute_score