# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import asyncio
import json
import logging
import os
import ast
from abc import ABC, abstractmethod
import textwrap
import autopep8

import regex as re
from pydantic import BaseModel

from verl.utils.rollout_trace import rollout_trace_op

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))


class FunctionCall(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""


class ToolParser(ABC):
    _registry: dict[str, type["ToolParser"]] = {}

    def __init__(self, tokenizer) -> None:
        self.tokenizer = tokenizer

    @abstractmethod
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:
        """Extract tool calls from the responses.

        Args:
            responses_ids (List[int]): The ids of the responses.

        Returns:
            Tuple[str, List[FunctionCall]]: Content and extracted tool calls.
        """
        raise NotImplementedError

    @classmethod
    def get_tool_parser(cls, name: str, tokenizer):
        if name not in cls._registry:
            raise ValueError(f"Unknown tool parser: {name}")
        return cls._registry[name](tokenizer)

    @classmethod
    def register(cls, name: str):
        def decorator(subclass: type[ToolParser]) -> type[ToolParser]:
            cls._registry[name] = subclass
            return subclass

        return decorator

def extract_python_code(action_string: str) -> str:
    tool_call_match = re.findall(r'<code>(.*?)</code>', action_string, re.DOTALL)
    if not tool_call_match: return None
    last_code_block = tool_call_match[-1]
    # Try to match the ```python ... ``` fenced format
    pattern = r'```python\s*\n(.*?)\n```'
    code_match = re.findall(pattern, last_code_block, re.DOTALL)
    if code_match: return code_match[-1]
    # Match "python" followed by a newline, up to the end of the code block
    pattern2 = r'^python\s*\n(.*)$'
    code_match2 = re.search(pattern2, last_code_block.strip(), re.DOTALL)
    if code_match2: return code_match2.group(1).strip()
    return None

def fix_python_indentation(code):
    try:
        formatted_code = autopep8.fix_code(code, options={'aggressive': 2})
        return formatted_code
    except Exception:
        print('Code has syntax errors, cannot reliably fix indentation!')
        return code

@ToolParser.register("hermes")
class HermesToolParser(ToolParser):
    """Adapted from https://github.com/vllm-project/vllm/blob/v0.9.1/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py"""

    def __init__(self, tokenizer) -> None:
        super().__init__(tokenizer)

        self.tool_call_start_token: str = "<code>"
        self.tool_call_end_token: str = "</code>"
        self.tool_call_regex = re.compile(r"<code>(.*?)</code>", re.DOTALL)

    @rollout_trace_op
    async def extract_tool_calls(self, responses_ids: list[int]) -> tuple[str, list[FunctionCall]]:
        loop = asyncio.get_running_loop()
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)

        code_str = extract_python_code(text)
        if not code_str: return text, []
        code_str = fix_python_indentation(code_str)

        function_calls = []
        try:
            name = "vlm_coding"
            arguments = dict()
            arguments["code_str"] = code_str
            logger.warning(f"SUCCESS TOOL CALL: {name}")
            function_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))
        except Exception as e:
            logger.error(f"Failed to decode tool call: {e}")
            return text, []

        # remaing text exclude tool call tokens
        content = self.tool_call_regex.sub("", text)

        return content, function_calls
